import SwiftUI

// MARK: — MockData
// Faz C scaffold — 4 packs × 60 levels each = 240 total.
// Replace with real persistence in Faz D/E.

struct Pack: Identifiable, Hashable {
    let id: String
    let title: String
    let subtitle: String
    let gridSize: Int       // 5, 6, 7, 8
    let levelCount: Int     // 60
    let completedCount: Int
    let isLocked: Bool
    let accentColor: Color
    let iconName: String

    /// Alias for iconName — used by views that reference pack.iconSymbol.
    var iconSymbol: String { iconName }
    /// Alias for subtitle — displayed as a grid-size badge, e.g. "5×5 grid".
    var gridLabel: String { subtitle }
    /// Completed fraction 0.0–1.0 for progress bars.
    var progressFraction: CGFloat {
        levelCount > 0 ? CGFloat(completedCount) / CGFloat(levelCount) : 0
    }

    // MARK: — H-1 Localization keys (used by ShopView)

    /// Raw String key for NSLocalizedString calls (a11y labels).
    /// e.g. "pack.cozy_beginnings.title"
    var rawTitleKey: String {
        "pack.\(id.replacingOccurrences(of: "-", with: "_")).title"
    }
    /// LocalizedStringKey variant — used in SwiftUI Text(pack.titleKey).
    var titleKey: LocalizedStringKey { LocalizedStringKey(rawTitleKey) }
    /// Plain localized String — for nav titles, a11y labels, alert interpolation.
    var localizedTitle: String { NSLocalizedString(rawTitleKey, comment: "") }
    /// LocalizedStringKey for the grid-size badge, e.g. "pack.grid_label.5".
    /// NOTE: build the key as a String FIRST — `LocalizedStringKey("…\(x)…")`
    /// treats the interpolation as a format ARGUMENT (key becomes "…%lld…"),
    /// so the lookup fails and the raw key renders. A String variable avoids it.
    var gridLabelKey: LocalizedStringKey {
        let key = "pack.grid_label.\(gridSize)"
        return LocalizedStringKey(key)
    }
}

struct LevelItem: Identifiable, Hashable {
    let id: String
    let index: Int          // 1..60 in pack
    let isCompleted: Bool
    let isLocked: Bool
    let stars: Int          // 0..3

    /// Alias for index — used by views that reference level.number.
    var number: Int { index }
}

enum MockData {

    /// Levels per pack. 17 packs × 60 = 1020 total campaign levels.
    static let levelsPerPack = 60

    /// Pack catalog. All packs are free and gated by PROGRESSION (energy + Premium
    /// monetize play now — not per-pack IAP). Procedurally generated by packId, so
    /// adding a row here adds 60 fresh levels.
    static let allPacks: [Pack] = {
        // (id, English title, gridSize, SF icon, accent)
        let specs: [(String, String, Int, String, Color)] = [
            ("cozy-beginnings",  "Cozy Beginnings",  5, "leaf.fill",            AppColors.blockLavender),
            ("spice-route",      "Spice Route",      6, "cup.and.saucer.fill",  AppColors.blockPeach),
            ("mambo-nights",     "Mambo Nights",     7, "moon.stars.fill",      AppColors.blockBlush),
            ("woodland-retreat", "Woodland Retreat", 8, "tree.fill",            AppColors.blockSage),
            ("morning-meadow",   "Morning Meadow",   5, "sun.max.fill",         AppColors.blockCream),
            ("amber-harbor",     "Amber Harbor",     6, "sailboat.fill",        AppColors.blockPeach),
            ("velvet-dusk",      "Velvet Dusk",      7, "sparkles",             AppColors.blockLavender),
            ("hearth-tales",     "Hearth Tales",     8, "flame.fill",           AppColors.blockBlush),
            ("misty-grove",      "Misty Grove",      5, "cloud.fill",           AppColors.blockSage),
            ("honey-fields",     "Honey Fields",     6, "drop.fill",            AppColors.blockCream),
            ("lantern-lane",     "Lantern Lane",     7, "lightbulb.fill",       AppColors.blockPeach),
            ("frost-haven",      "Frost Haven",      8, "snowflake",            AppColors.blockLavender),
            ("garden-party",     "Garden Party",     5, "leaf.circle.fill",     AppColors.blockSage),
            ("ocean-breeze",     "Ocean Breeze",     6, "water.waves",          AppColors.blockBlush),
            ("starlit-peak",     "Starlit Peak",     7, "mountain.2.fill",      AppColors.blockLavender),
            ("cocoa-cabin",      "Cocoa Cabin",      8, "house.fill",           AppColors.blockPeach),
            ("aurora-vale",      "Aurora Vale",      8, "sparkles.tv.fill",     AppColors.blockDustyOlive),
        ]
        return specs.enumerated().map { idx, s in
            Pack(
                id: s.0,
                title: s.1,
                subtitle: "\(s.2)×\(s.2) grid",
                gridSize: s.2,
                levelCount: levelsPerPack,
                completedCount: idx == 0 ? 12 : (idx == 1 ? 4 : 0),
                isLocked: false,
                accentColor: s.4,
                iconName: s.3
            )
        }
    }()

    /// Total campaign levels across all packs (single source of truth).
    static var totalLevels: Int { allPacks.reduce(0) { $0 + $1.levelCount } }

    // MARK: — Continue helpers (used by MainMenuView)

    /// First unlocked pack that has at least one completed level.
    static var continuePack: Pack? {
        allPacks.first { !$0.isLocked && $0.completedCount > 0 }
    }

    /// The next unplayed level in continuePack.
    static var continueLevel: LevelItem? {
        guard let pack = continuePack else { return nil }
        let nextIndex = pack.completedCount + 1
        return LevelItem(
            id: "\(pack.id)-\(nextIndex)",
            index: nextIndex,
            isCompleted: false,
            isLocked: false,
            stars: 0
        )
    }

    static func levels(in packId: String) -> [LevelItem] {
        let completedUpTo: Int
        switch packId {
        case "cozy-beginnings": completedUpTo = 12
        case "spice-route":     completedUpTo = 4
        default:                completedUpTo = 0
        }
        return (1...60).map { i in
            let done   = i <= completedUpTo
            let locked = !done && i > completedUpTo + 1
            return LevelItem(
                id: "\(packId)-\(i)",
                index: i,
                isCompleted: done,
                isLocked: locked,
                stars: done ? [1, 2, 3][abs("\(packId)-\(i)".hashValue) % 3] : 0
            )
        }
    }
}
